### ISSUE TITLE
Small Syntax Error detection mistake

### ISSUE THREAD

**Issue by vishal272** [abartelsmeier/language-splus#1]
Seems to Detect that there is an error when specifing number of digits for a string placeholder in a trace or make string with %02u which adds leading a zero if  the variable we are trying to print is 1 digit long.

![image](https://user-images.githubusercontent.com/16915917/38078165-4da45e32-3333-11e8-9b41-7218c9198a47.png)

**Comment by abtmr** [comment]
Many thanks for finding the problem, it's quite a simple one to fix. Will do so shortly!

**Comment by abtmr** [comment]
Could you please update to v0.1.1 using `apm update language-splus`, then reopen Atom and verify that it is fixed? Thanks

**Comment by vishal272** [comment]
yup its been fixed. Thank you very much.

**Comment by abtmr** [comment]
you're welcome!
