### ISSUE TITLE
Missing Syntax Detection for a couple of Keywords

### ISSUE THREAD

**Issue by vishal272** [abartelsmeier/language-splus#2]
I seem to have also noticed that UDP_SOCKET, TCP_SERVER, HELP_PDF_FILE and HELP_END are missing from keywords

![image](https://user-images.githubusercontent.com/16915917/38087626-b369811c-3350-11e8-8e38-7ca36fbe0fa8.png)
![image](https://user-images.githubusercontent.com/16915917/38087744-2a26247c-3351-11e8-86ba-b59b23f6ac25.png)

**Comment by abtmr** [comment]
have a try with v0.1.2

**Comment by vishal272** [comment]
Yup its fixed had a look around to see if anything else was missing but cant seem to find anything if i do ill send another issue report here. Thank you again

**Comment by abtmr** [comment]
sure thing, feel free to submit pull requests too if you feel like trying to fix something yourself!
